Fix unit test failure in gpstate on rocky8/centos7
After merging https://github.com/greenplum-db/gpdb/pull/15294, `test_PgPortIsActive_no_netstat_ss` gpstate unit test case started failing for rocky8 and centos7 platforms on prod pipeline with the error -
```
File "/tmp/build/9a968038/gpdb_src/gpMgmt/bin/gppylib/commands/unix.py", line 587, in __init__
logger.critical(
AttributeError: Mock object has no attribute 'critical'
```

The reason for this is that we have mocked the logger framework in the previous PR https://github.com/greenplum-db/gpdb/blob/dd223740668f8f84eed8b468e760704c94b73b76/gpMgmt/bin/gppylib/commands/test/unit/test_unit_unix.py#L11 and this mock is not cleaned up for subsequent unit test runs on theses platforms (not sure why). Since we have not mocked the `critical` attribute, we see the above error.

This commit fixes this by adding the `critical` attribute to the list.